name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk
    
    steps:
      - name: Checkout
        uses: https://gitea.com/actions/checkout@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Create Release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: build/libs/LoChat-*.jar
          api_key: ${{ secrets.RELEASE_TOKEN }}
